"""empty message

Revision ID: 1d5053fd1620
Revises: 
Create Date: 2017-08-31 11:25:07.223723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d5053fd1620'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('music',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.String(length=100), nullable=True),
    sa.Column('song_name', sa.String(length=100), nullable=True),
    sa.Column('artist_name', sa.String(length=100), nullable=True),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('music')
    # ### end Alembic commands ###
